services:
  php:
    build: ./backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - './backend/logs:/logs'
  react:
    build: ./frontend
    restart: always
    ports:
      - '8080:8080'
